# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Resume', link: 'https://drive.google.com/file/d/137czJCv75T-15iAEqo914a72Upxj5of4/view?usp=sharing'}
- {name: 'Ideas', folder: 'pages', file: 'ideas.html'}
- {name: 'Others', folder: 'pages', file: 'others.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/cwpark0418'}
- {icon: 'instagram', link: 'https://instagram.com/chaedoong0418'}
- {icon: 'envelope', link: 'mailto:cp3227@columbia.edu'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/chaewon-park-bb9b7a97'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
